BBBatScale/core/urls.py
from django.urls import path

from core import views
from django.contrib.auth.decorators import login_required


urlpatterns = [

    path('api/callback/bbb/', views.callback_bbb, name="callback_bbb"),
    path('api/recording/postporocessing/done/', views.recording_callback),
    path('api/instances/registration/', views.api_instance_registration, name="api_instance_registration"),
    path('instances/overview', views.instances_overview, name="instances_overview"),
    path('rooms/overview', views.rooms_overview, name="rooms_overview"),
    path('tenants/overview', views.tenant_overview, name="tenants_overview"),
    path('rooms/configs/overview', views.room_config_overview, name="room_configs_overview"),

    path('instance/create/', login_required(views.instance_create), name="instance_create"),
    path('instance/delete/<int:instance>', login_required(views.instance_delete), name="instance_delete"),
    path('instance/update/<int:instance>', login_required(views.instance_update), name="instance_update"),

    path('room/create/', login_required(views.room_create), name="room_create"),
    path('room/delete/<int:room>', login_required(views.room_delete), name="room_delete"),
    path('room/update/<int:room>', login_required(views.room_update), name="room_update"),

    path('statistics', views.statistics, name="statistics"),

    path('importexport', login_required(views.import_export), name="import_export"),
    path('export/json', login_required(views.export_download_json), name="export_download_json"),
    path('export/csv', login_required(views.export_download_csv), name="export_download_csv"),
    path('import/json', login_required(views.import_upload_json), name="import_upload_json"),
    path('import/csv', login_required(views.import_upload_csv), name="import_upload_csv"),

    path('room/config/create/', login_required(views.room_config_create), name="room_config_create"),
    path('room/config/delete/<int:room_config>', login_required(views.room_config_delete), name="room_config_delete"),
    path('room/config/update/<int:room_config>', login_required(views.room_config_update), name="room_config_update"),

    path('tenant/create/', login_required(views.tenant_create), name="tenant_create"),
    path('tenant/delete/<int:tenant>', login_required(views.tenant_delete), name="tenant_delete"),
    path('tenant/update/<int:tenant>', login_required(views.tenant_update), name="tenant_update"),

    path('recordings/overview/', login_required(views.recordings_list), name="recordings_list"),

    path('users/overview/', login_required(views.users_overview), name="users_overview"),
    path('user/create/', login_required(views.user_create), name="user_create"),
    path('user/change/password/', login_required(views.change_password), name="change_password"),
    path('user/delete/<int:user>', login_required(views.user_delete), name="user_delete"),
    path('user/update/<int:user>', login_required(views.user_update), name="user_update"),

    path('join/create/meeting/<str:room>', views.join_or_create_meeting, name="join_or_create_meeting"),
    path('create/meeting/<str:room>', views.create_meeting, name="create_meeting"),
    path('join/meeting/<str:room>', views.join_meeting, name="join_meeting"),
    path('join/meeting/anon/', views.session_set_username, name="session_set_username"),
    path('meeting/status/<str:meeting_id>', views.get_meeting_status, name="get_meeting_status"),
    path('room/meeting/end/<int:room_pk>', login_required(views.force_end_meeting), name="force_end_meeting"),
]

BBBatScale/core/models.py
from math import ceil

from django.db import transaction

from django.db import models
from django.db.models import Sum
from django.utils.crypto import get_random_string
from django.utils.timezone import now

from core.utils import BigBlueButton

import logging

from core.constants import INSTANCE_STATES, INSTANCE_STATE_WAITING_RESPONSE, INSTANCE_STATE_ERROR, \
    SCHEDULING_STRATEGY_LEAST_PARTICIPANTS, INSTANCE_STATE_UP, INSTANCE_STATE_DISABLED, \
    SCHEDULING_STRATEGY_LEAST_UTILIZATION, GUEST_POLICY, GUEST_POLICY_ALLOW, ROOM_STATE, ROOM_STATE_INACTIVE, \
    SCHEDULING_STRATEGIES, ROOM_STATE_ACTIVE

logger = logging.getLogger(__name__)


class Tenant(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    notifications_emails = models.TextField(null=True, blank=True)
    token_registration = models.CharField(max_length=255, null=True, blank=True)
    scheduling_strategy = models.CharField(max_length=255, choices=SCHEDULING_STRATEGIES,
                                           default=SCHEDULING_STRATEGY_LEAST_UTILIZATION)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.token_registration:
            self.token_registration = get_random_string(length=10)
        super(Tenant, self).save(*args, **kwargs)

    def get_current_participant_count(self):
        return self.room_set.all().aggregate(Sum('participant_count'))['participant_count__sum']

    def get_utilization(self):
        usage = 0
        for instance in self.get_instances_up():
            usage = usage + instance.get_utilization()
        return ceil(usage)

    def get_utilization_max(self):
        sum = 0
        for instance in self.get_instances_up():
            sum = sum + instance.videostream_count_max
        return ceil(sum)

    def get_utilization_percent(self):
        max = self.get_utilization_max()
        return 0 if max <= 0 else int(round((self.get_utilization()) / self.get_utilization_max(), 2) * 100)

    def get_instance_for_room(self):
        instance_to_be = None

        logger.info("Selecting new instance for scheduling with strategy: {}".format(self.scheduling_strategy))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_LEAST_PARTICIPANTS:
            min_count = 1000
            for instance in self.instance_set.filter(state=INSTANCE_STATE_UP):
                pc = instance.get_participant_count()
                if pc < min_count:
                    min_count = pc
                    instance_to_be = instance
                    logger.info("Best candidate so far: {}".format(instance_to_be))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_LEAST_UTILIZATION:
            min_count = 1000
            for instance in self.instance_set.filter(state=INSTANCE_STATE_UP):
                pc = instance.get_utilization()
                if pc < min_count:
                    min_count = pc
                    instance_to_be = instance
                    logger.info("Best candidate so far: {}".format(instance_to_be))

        logger.info("Selected : {}".format(instance_to_be))

        return instance_to_be

    def get_instances_up(self):
        return self.instance_set.filter(state=INSTANCE_STATE_UP)


class RoomConfiguration(models.Model):
    name = models.CharField(max_length=255, unique=True)
    mute_on_start = models.BooleanField(default=True)
    all_moderator = models.BooleanField(default=False)
    everyone_can_start = models.BooleanField(default=False)
    authenticated_user_can_start = models.BooleanField(default=False)
    guest_policy = models.CharField(max_length=30, choices=GUEST_POLICY, default=GUEST_POLICY_ALLOW, blank=True)
    allow_guest_entry = models.BooleanField(default=False)
    access_code = models.CharField(max_length=255, null=True, blank=True)
    access_code_guests = models.CharField(max_length=255, null=True, blank=True)
    disable_cam = models.BooleanField(default=False)
    disable_mic = models.BooleanField(default=False)
    allow_recording = models.BooleanField(default=False)
    disable_private_chat = models.BooleanField(default=False)
    disable_public_chat = models.BooleanField(default=False)
    disable_note = models.BooleanField(default=False)
    url = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Instance(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.SET_NULL, null=True)
    dns = models.CharField(max_length=255, unique=True)
    state = models.CharField(max_length=255, choices=INSTANCE_STATES, default=INSTANCE_STATE_WAITING_RESPONSE)
    datacenter = models.CharField(max_length=255, null=True, blank=True)
    shared_secret = models.CharField(max_length=255, null=True, blank=True)
    participant_count_max = models.PositiveIntegerField(default=250)
    videostream_count_max = models.PositiveIntegerField(default=25)

    last_health_check = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('tenant', 'dns',)

    def __str__(self):
        return self.dns

    # quick and dirty util cals.
    def get_utilization(self):
        audio_video_factor = self.participant_count_max / self.videostream_count_max
        audio_usage = self.get_participant_count() / audio_video_factor
        video_usage = self.get_videostream_count()
        total_usage = audio_usage + video_usage

        return 0 if total_usage <= 0 else total_usage

    def get_utilization_percent(self):
        return int(round((self.get_utilization()) / self.videostream_count_max, 2) * 100)

    # todo change to service.py
    def collect_stats(self):
        logger.info("Health Check started for.... {}".format(self.dns))
        # skip disabled instances
        if self.state != INSTANCE_STATE_DISABLED:
            try:
                bbb = BigBlueButton(self.dns, self.shared_secret)
                meetings = bbb.get_meetings()

                if meetings:
                    for meeting in meetings:
                        logger.info("Starting transaction for updating room {}".format(meeting['meetingName']))
                        with transaction.atomic():
                            room = Room.objects.get_or_create(name=meeting['meetingName'])[0]
                            room.instance = self
                            room.state = ROOM_STATE_ACTIVE
                            room.tenant = self.tenant
                            room.participant_count = meeting['participantCount']
                            room.videostream_count = meeting['videoCount']
                            room.is_breakout = True if meeting['isBreakout'] == 'true' else False
                            room.last_running = now()
                            room.save()
                        logger.info("Ending transaction for updating room {}".format(meeting['meetingName']))

                self.state = INSTANCE_STATE_UP

            except Exception as e:
                logger.error(e)
                logger.error("setting instance state of {} to ERROR".format(self.dns))
                self.state = INSTANCE_STATE_ERROR

            self.last_health_check = now()
            self.save()
        logger.info("Health Check finished for.... {}".format(self.dns))

    def get_participant_count(self):
        count = self.room_set.all().aggregate(Sum('participant_count'))['participant_count__sum']
        return count if count else 0

    def get_videostream_count(self):
        count = self.room_set.all().aggregate(Sum('videostream_count'))['videostream_count__sum']
        return count if count else 0


class Room(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.SET_NULL, null=True)
    instance = models.ForeignKey(Instance, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=255, unique=True, null=True)
    config = models.ForeignKey(RoomConfiguration, on_delete=models.SET_NULL, blank=True, null=True)
    meeting_id = models.CharField(max_length=255, null=True, blank=True, unique=True)
    is_public = models.BooleanField(default=True)
    state = models.CharField(max_length=30, choices=ROOM_STATE, default=ROOM_STATE_INACTIVE)

    # Room Config
    mute_on_start = models.BooleanField(default=True)
    all_moderator = models.BooleanField(default=False)
    everyone_can_start = models.BooleanField(default=False)
    authenticated_user_can_start = models.BooleanField(default=False)
    guest_policy = models.CharField(max_length=30, choices=GUEST_POLICY, default=GUEST_POLICY_ALLOW, blank=True)
    allow_guest_entry = models.BooleanField(default=False)
    access_code = models.CharField(max_length=255, null=True, blank=True)
    access_code_guests = models.CharField(max_length=255, null=True, blank=True)
    disable_cam = models.BooleanField(default=False)
    disable_mic = models.BooleanField(default=False)
    allow_recording = models.BooleanField(default=False)
    disable_private_chat = models.BooleanField(default=False)
    disable_public_chat = models.BooleanField(default=False)
    disable_note = models.BooleanField(default=False)
    url = models.CharField(max_length=255, null=True, blank=True)

    attendee_pw = models.CharField(max_length=255, null=True, blank=True)
    moderator_pw = models.CharField(max_length=255, null=True, blank=True)

    comment_public = models.CharField(max_length=255, null=True, blank=True)
    comment_private = models.CharField(max_length=255, null=True, blank=True)

    click_counter = models.PositiveIntegerField(default=0)

    participant_count = models.PositiveIntegerField(default=0)
    videostream_count = models.PositiveIntegerField(default=0)

    is_breakout = models.BooleanField(default=False)

    event_collection_strategy = models.CharField(max_length=255, null=True, blank=True)

BBBatScale/templates/base.html
{% load static %}
{% load in_group %}
{% load i18n %}
<!DOCTYPE html>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ general_parameter.page_title }}</title>
    {% if general_parameter.favicon_link %}
        <link rel="shortcut icon" href="{{ general_parameter.favicon_link }}">
    {% else %}
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    {% block styles %}
    {% endblock %}


</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
    <nav aria-label="Top Nav" class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><em class="fas fa-bars"></em></a>
            </li>

            <li class="nav-item d-sm-inline-block">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="nav-link">{% trans "Logout" %}</a>
                {% else %}
                    <a href="{% url 'login' %}" class="nav-link">{% trans "Login" %}</a>
                {% endif %}
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item d-sm-inline-block">
                    <a href="{% url 'change_password' %}" class="nav-link">{% trans "Change password" %}</a>
                </li>
            {% endif %}

        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item d-sm-inline-block mr-3">
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language" onchange="this.form.submit()" class="select form-control">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                    selected{% endif %}>
                                {{ language.code }}
                            </option>
                        {% endfor %}
                    </select>
                </form>
            </li>
        </ul>

    </nav>

    <aside aria-label="Side Nav" class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="/" class="brand-link">
            {% if general_parameter.logo_link %}
                <img src="{{ general_parameter.logo_link }}" alt="AdminLTE Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
            {% else %}
                <span class="brand-image img-circle" style="margin-top: 5.5px;">
                    B<em class="nav-icon fas fa-at "></em>S
                </span>
            {% endif %}


            <span class="brand-text font-weight-light">{% trans "Virtual Rooms" %}</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">

            {% if request.user.is_authenticated %}
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{% static 'img/default_profile.png' %}" class="img-circle elevation-2"
                             alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">{{ request.user.last_name }}, {{ request.user.first_name }}</a>
                    </div>
                </div>
            {% endif %}

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">


                    <li class="nav-item">
                        <a href="/" class="nav-link">
                            <em class="nav-icon fas fa-graduation-cap"></em>
                            <p>{% trans "Home" %}</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'statistics' %}" class="nav-link">
                            <em class="nav-icon fas fa-chart-line"></em>
                            <p>{% trans "Statistics" %}</p>
                        </a>
                        </a>
                    </li>

                    {% if request.user.is_staff %}

                        <li class="nav-item">
                            <a href="/admin/" class="nav-link" target="_blank">
                                <em class="nav-icon fas fa-tv"></em>
                                <p>{% trans "Admin" %}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'users_overview' %}" class="nav-link">
                                <em class="nav-icon fas fa-user"></em>
                                <p>{% trans "Users" %}</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url "tenants_overview" %}" class="nav-link">
                                <em class="nav-icon fas fa-users"></em>
                                <p>{% trans "Tenants" %}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'rooms_overview' %}" class="nav-link">
                                <em class="nav-icon fas fa-person-booth"></em>
                                <p>{% trans "Rooms" %}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'instances_overview' %}" class="nav-link">
                                <em class="nav-icon fas fa-server"></em>
                                <p>{% trans "Server" %}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'import_export' %}" class="nav-link">
                                <em class="nav-icon fas fa-retweet"></em>
                                <p>{% trans "Import/Export" %}</p>
                            </a>
                        </li>
                    {% endif %}
                    {% if request.user|in_group:"Teacher" %}
                        <li class="nav-item">
                            <a href="{% url 'room_configs_overview' %}" class="nav-link">
                                <em class="nav-icon fas fa-cubes"></em>
                                <p>{% trans "Room Types" %}</p>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'recordings_list' %}" class="nav-link">
                            <em class="nav-icon fas fa-video"></em>
                            <p>{% trans "Recordings" %}</p>
                        </a>
                    </li>
                    {% if general_parameter.faq_url %}
                        <li class="nav-item">
                            <a href="{{ general_parameter.faq_url }}" target="_blank"
                               class="nav-link" rel="noopener noreferrer">
                                <em class="nav-icon fas fa-question-circle"></em>
                                <p>{% trans "FAQ" %}</p>
                            </a>
                        </li>
                    {% endif %}
                    {% if general_parameter.feedback_email %}
                        <li class="nav-item">
                            <a href="mailto:{{ general_parameter.feedback_email }}?subject=Feedback BBB Portal"
                               class="nav-link">
                                <em class="nav-icon fas fa-comment-dots"></em>
                                <p>{% trans "Feedback" %}</p>
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            {% block page_title %}
            {% endblock %}
        </div>
        <div class="content">
            <div class="container-fluid">

                {% if messages %}
                    <div class="row">
                        <div class="col-12">
                            {% for message in messages %}

                                {% if message.tags == 'info' %}
                                    <div class="alert alert-info alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                        </button>
                                        <h5><em class="icon fas fa-info"></em> {% trans "Info" %}!</h5> {{ message }}
                                    </div>
                                {% endif %}

                                {% if message.tags == 'success' %}
                                    <div class="alert alert-success alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                        </button>
                                        <h5><em class="icon fas fa-check"></em> {% trans "Success" %}!
                                        </h5> {{ message }}
                                    </div>
                                {% endif %}

                                {% if message.tags == 'warning' %}
                                    <div class="alert alert-warning alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                        </button>
                                        <h5><em class="icon fas fa-exclamation-triangle"></em> {% trans "Warning" %}!
                                        </h5> {{ message }}
                                    </div>
                                {% endif %}

                                {% if message.tags == 'error' %}
                                    <div class="alert alert-danger alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                        </button>
                                        <h5><em class="icon fas fa-ban"></em> {% trans "Error" %}!</h5> {{ message }}
                                    </div>
                                {% endif %}

                            {% endfor %}
                        </div>
                    </div>
                {% endif %}


                {% block content %}
                {% endblock %}
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->


    </div>
    <!-- /.content-wrapper -->


    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            <!--
            Admin Theme by <a href="https://adminlte.io">AdminLTE.io</a> -->
        </div>
        {% if general_parameter.footer %}
            {{ general_parameter.footer|safe }}
        {% endif %}
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- toastr Plugin -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
{% block scripts %}
{% endblock %}


</body>
</html>

BBBatScale/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
    {% if general_parameter.latest_news %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><em class="icon fas fa-info"></em>{% trans "Latest News!" %}</h5> {{ general_parameter.latest_news|safe }}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body login-card-body">
                    <p class="login-box-msg">{% trans "Sign in to start using the rooms" %}</p>

                    <form action="{% url 'login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control"
                                   placeholder="Account" name="username">
                            <input type="hidden" name="next" value="{{ next }}"/>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-user"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">{% trans "Sign In" %}</button>

                            </div>
                            <!-- /.col -->
                            <div class="col-8">

                            </div>
                            <!-- /.col -->
                        </div>
                    </form>
                </div>
                <!-- /.login-card-body -->
            </div>
        </div>

    </div>



{% endblock %}

BBBatScale/templates/snippet_progress_bar.html
{% if progress < 50 %}
<div class="progress progress-xs">
<div class="progress-bar bg-primary" style="width: {{ progress }}%"></div>
</div>
{% elif progress > 70 %}
<div class="progress progress-xs">
<div class="progress-bar bg-danger" style="width: {{ progress }}%"></div>
</div>
{% else %}
<div class="progress progress-xs">
<div class="progress-bar bg-warning" style="width: {{ progress }}%"></div>
</div>
{% endif %}

BBBatScale/templates/snippet_room_state.html
{% if state == "ACTIVE" %}
    <span class="badge badge-success">{{ room.get_state_display }}</span>
{% elif state == "INACTIVE" %}
    <span class="badge badge-secondary">{{ room.get_state_display }}</span>
{% else %}
    <span class="badge badge-warning">{{ room.get_state_display }}</span>
{% endif %}