BBBatScale/core/urls.py
from django.urls import path

from core import views
from django.contrib.auth.decorators import login_required


urlpatterns = [

    path('api/callback/bbb/', views.callback_bbb, name="callback_bbb"),
    path('api/recording/postporocessing/done/', views.recording_callback),
    path('api/instances/registration/', views.api_instance_registration, name="api_instance_registration"),
    path('instances/overview', views.instances_overview, name="instances_overview"),
    path('rooms/overview', views.rooms_overview, name="rooms_overview"),
    path('tenants/overview', views.tenant_overview, name="tenants_overview"),
    path('rooms/configs/overview', views.room_config_overview, name="room_configs_overview"),

    path('instance/create/', login_required(views.instance_create), name="instance_create"),
    path('instance/delete/<int:instance>', login_required(views.instance_delete), name="instance_delete"),
    path('instance/update/<int:instance>', login_required(views.instance_update), name="instance_update"),

    path('room/create/', login_required(views.room_create), name="room_create"),
    path('room/delete/<int:room>', login_required(views.room_delete), name="room_delete"),
    path('room/update/<int:room>', login_required(views.room_update), name="room_update"),

    path('statistics', views.statistics, name="statistics"),

    path('importexport', login_required(views.import_export), name="import_export"),
    path('export/json', login_required(views.export_download_json), name="export_download_json"),
    path('export/csv', login_required(views.export_download_csv), name="export_download_csv"),
    path('import/json', login_required(views.import_upload_json), name="import_upload_json"),
    path('import/csv', login_required(views.import_upload_csv), name="import_upload_csv"),

    path('room/config/create/', login_required(views.room_config_create), name="room_config_create"),
    path('room/config/delete/<int:room_config>', login_required(views.room_config_delete), name="room_config_delete"),
    path('room/config/update/<int:room_config>', login_required(views.room_config_update), name="room_config_update"),

    path('tenant/create/', login_required(views.tenant_create), name="tenant_create"),
    path('tenant/delete/<int:tenant>', login_required(views.tenant_delete), name="tenant_delete"),
    path('tenant/update/<int:tenant>', login_required(views.tenant_update), name="tenant_update"),

    path('recordings/overview/', login_required(views.recordings_list), name="recordings_list"),

    path('users/overview/', login_required(views.users_overview), name="users_overview"),
    path('user/create/', login_required(views.user_create), name="user_create"),
    path('user/change/password/', login_required(views.change_password), name="change_password"),
    path('user/delete/<int:user>', login_required(views.user_delete), name="user_delete"),
    path('user/update/<int:user>', login_required(views.user_update), name="user_update"),

    path('join/create/meeting/<str:room>', views.join_or_create_meeting, name="join_or_create_meeting"),
    path('create/meeting/<str:room>', views.create_meeting, name="create_meeting"),
    path('join/meeting/<str:room>', views.join_meeting, name="join_meeting"),
    path('join/meeting/anon/', views.session_set_username, name="session_set_username"),
    path('meeting/status/<str:meeting_id>', views.get_meeting_status, name="get_meeting_status"),
    path('room/meeting/end/<int:room_pk>', login_required(views.force_end_meeting), name="force_end_meeting"),
]

BBBatScale/core/models.py
from math import ceil

from django.db import transaction

from django.db import models
from django.db.models import Sum
from django.utils.crypto import get_random_string
from django.utils.timezone import now

from core.utils import BigBlueButton

import logging

from core.constants import INSTANCE_STATES, INSTANCE_STATE_WAITING_RESPONSE, INSTANCE_STATE_ERROR, \
    SCHEDULING_STRATEGY_LEAST_PARTICIPANTS, INSTANCE_STATE_UP, INSTANCE_STATE_DISABLED, \
    SCHEDULING_STRATEGY_LEAST_UTILIZATION, GUEST_POLICY, GUEST_POLICY_ALLOW, ROOM_STATE, ROOM_STATE_INACTIVE, \
    SCHEDULING_STRATEGIES, ROOM_STATE_ACTIVE

logger = logging.getLogger(__name__)


class Tenant(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    notifications_emails = models.TextField(null=True, blank=True)
    token_registration = models.CharField(max_length=255, null=True, blank=True)
    scheduling_strategy = models.CharField(max_length=255, choices=SCHEDULING_STRATEGIES,
                                           default=SCHEDULING_STRATEGY_LEAST_UTILIZATION)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.token_registration:
            self.token_registration = get_random_string(length=10)
        super(Tenant, self).save(*args, **kwargs)

    def get_current_participant_count(self):
        return self.room_set.all().aggregate(Sum('participant_count'))['participant_count__sum']

    def get_utilization(self):
        usage = 0
        for instance in self.get_instances_up():
            usage = usage + instance.get_utilization()
        return ceil(usage)

    def get_utilization_max(self):
        sum = 0
        for instance in self.get_instances_up():
            sum = sum + instance.videostream_count_max
        return ceil(sum)

    def get_utilization_percent(self):
        max = self.get_utilization_max()
        return 0 if max <= 0 else int(round((self.get_utilization()) / self.get_utilization_max(), 2) * 100)

    def get_instance_for_room(self):
        instance_to_be = None

        logger.info("Selecting new instance for scheduling with strategy: {}".format(self.scheduling_strategy))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_LEAST_PARTICIPANTS:
            min_count = 1000
            for instance in self.instance_set.filter(state=INSTANCE_STATE_UP):
                pc = instance.get_participant_count()
                if pc < min_count:
                    min_count = pc
                    instance_to_be = instance
                    logger.info("Best candidate so far: {}".format(instance_to_be))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_LEAST_UTILIZATION:
            min_count = 1000
            for instance in self.instance_set.filter(state=INSTANCE_STATE_UP):
                pc = instance.get_utilization()
                if pc < min_count:
                    min_count = pc
                    instance_to_be = instance
                    logger.info("Best candidate so far: {}".format(instance_to_be))

        logger.info("Selected : {}".format(instance_to_be))

        return instance_to_be

    def get_instances_up(self):
        return self.instance_set.filter(state=INSTANCE_STATE_UP)


class RoomConfiguration(models.Model):
    name = models.CharField(max_length=255, unique=True)
    mute_on_start = models.BooleanField(default=True)
    all_moderator = models.BooleanField(default=False)
    everyone_can_start = models.BooleanField(default=False)
    authenticated_user_can_start = models.BooleanField(default=False)
    guest_policy = models.CharField(max_length=30, choices=GUEST_POLICY, default=GUEST_POLICY_ALLOW, blank=True)
    allow_guest_entry = models.BooleanField(default=False)
    access_code = models.CharField(max_length=255, null=True, blank=True)
    access_code_guests = models.CharField(max_length=255, null=True, blank=True)
    disable_cam = models.BooleanField(default=False)
    disable_mic = models.BooleanField(default=False)
    allow_recording = models.BooleanField(default=False)
    disable_private_chat = models.BooleanField(default=False)
    disable_public_chat = models.BooleanField(default=False)
    disable_note = models.BooleanField(default=False)
    url = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Instance(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.SET_NULL, null=True)
    dns = models.CharField(max_length=255, unique=True)
    state = models.CharField(max_length=255, choices=INSTANCE_STATES, default=INSTANCE_STATE_WAITING_RESPONSE)
    datacenter = models.CharField(max_length=255, null=True, blank=True)
    shared_secret = models.CharField(max_length=255, null=True, blank=True)
    participant_count_max = models.PositiveIntegerField(default=250)
    videostream_count_max = models.PositiveIntegerField(default=25)

    last_health_check = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('tenant', 'dns',)

    def __str__(self):
        return self.dns

    # quick and dirty util cals.
    def get_utilization(self):
        audio_video_factor = self.participant_count_max / self.videostream_count_max
        audio_usage = self.get_participant_count() / audio_video_factor
        video_usage = self.get_videostream_count()
        total_usage = audio_usage + video_usage

        return 0 if total_usage <= 0 else total_usage

    def get_utilization_percent(self):
        return int(round((self.get_utilization()) / self.videostream_count_max, 2) * 100)

    # todo change to service.py
    def collect_stats(self):
        logger.info("Health Check started for.... {}".format(self.dns))
        # skip disabled instances
        if self.state != INSTANCE_STATE_DISABLED:
            try:
                bbb = BigBlueButton(self.dns, self.shared_secret)
                meetings = bbb.get_meetings()

                if meetings:
                    for meeting in meetings:
                        logger.info("Starting transaction for updating room {}".format(meeting['meetingName']))
                        with transaction.atomic():
                            room = Room.objects.get_or_create(name=meeting['meetingName'])[0]
                            room.instance = self
                            room.state = ROOM_STATE_ACTIVE
                            room.tenant = self.tenant
                            room.participant_count = meeting['participantCount']
                            room.videostream_count = meeting['videoCount']
                            room.is_breakout = True if meeting['isBreakout'] == 'true' else False
                            room.last_running = now()
                            room.save()
                        logger.info("Ending transaction for updating room {}".format(meeting['meetingName']))

                self.state = INSTANCE_STATE_UP

            except Exception as e:
                logger.error(e)
                logger.error("setting instance state of {} to ERROR".format(self.dns))
                self.state = INSTANCE_STATE_ERROR

            self.last_health_check = now()
            self.save()
        logger.info("Health Check finished for.... {}".format(self.dns))

    def get_participant_count(self):
        count = self.room_set.all().aggregate(Sum('participant_count'))['participant_count__sum']
        return count if count else 0

    def get_videostream_count(self):
        count = self.room_set.all().aggregate(Sum('videostream_count'))['videostream_count__sum']
        return count if count else 0


class Room(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.SET_NULL, null=True)
    instance = models.ForeignKey(Instance, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=255, unique=True, null=True)
    config = models.ForeignKey(RoomConfiguration, on_delete=models.SET_NULL, blank=True, null=True)
    meeting_id = models.CharField(max_length=255, null=True, blank=True, unique=True)
    is_public = models.BooleanField(default=True)
    state = models.CharField(max_length=30, choices=ROOM_STATE, default=ROOM_STATE_INACTIVE)

    # Room Config
    mute_on_start = models.BooleanField(default=True)
    all_moderator = models.BooleanField(default=False)
    everyone_can_start = models.BooleanField(default=False)
    authenticated_user_can_start = models.BooleanField(default=False)
    guest_policy = models.CharField(max_length=30, choices=GUEST_POLICY, default=GUEST_POLICY_ALLOW, blank=True)
    allow_guest_entry = models.BooleanField(default=False)
    access_code = models.CharField(max_length=255, null=True, blank=True)
    access_code_guests = models.CharField(max_length=255, null=True, blank=True)
    disable_cam = models.BooleanField(default=False)
    disable_mic = models.BooleanField(default=False)
    allow_recording = models.BooleanField(default=False)
    disable_private_chat = models.BooleanField(default=False)
    disable_public_chat = models.BooleanField(default=False)
    disable_note = models.BooleanField(default=False)
    url = models.CharField(max_length=255, null=True, blank=True)

    attendee_pw = models.CharField(max_length=255, null=True, blank=True)
    moderator_pw = models.CharField(max_length=255, null=True, blank=True)

    comment_public = models.CharField(max_length=255, null=True, blank=True)
    comment_private = models.CharField(max_length=255, null=True, blank=True)

    click_counter = models.PositiveIntegerField(default=0)

    participant_count = models.PositiveIntegerField(default=0)
    videostream_count = models.PositiveIntegerField(default=0)

    is_breakout = models.BooleanField(default=False)

    event_collection_strategy = models.CharField(max_length=255, null=True, blank=True)

BBBatScale/core/templates/configure_room_for_meeting.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}

<section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Start a room" %}</h3>
                        </div>

                        <div class="card-body">
                            <p>
                                Room <strong>{{room}}</strong> is configured as <strong>{{ room.config }}</strong> with the following parameters. If you need a different configuration feel free to modify the parameters and press start.
                            </p>
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>

    </section>


{% endblock %}


{% block scripts %}

{% endblock scripts %}

BBBatScale/core/templates/import_export.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    {% if uniq_constraints %}
        <div class="row mt-2">
            <div class="col-md-6">
                <strong>multiple unique names detected: </strong> <br>

                {% for dup in uniq_constraints %}
                    => {{ dup }} <br>
                {% endfor %}
                <br>
                <br>
            </div>
        </div>
    {% else %}
        <div class="row mt-2">
            <div class="col-md-6">
                Import / Export
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-2">
                            <a class="btn btn-primary" href="{% url 'export_download_json' %}"> Download Export
                                JSON </a>
                        </div>
                        <div class="col-10">
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'import_upload_json' %}">
                                {% csrf_token %}
                                <input type="file" name="document">
                                <button class="btn btn-primary" type="submit"> Upload Import JSON</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="card-box">
                    <div class="row">
                        <div class="col-2">
                            <a class="btn btn-primary" href="{% url 'export_download_csv' %}"> Download Export
                                CSV </a>
                        </div>
                        <div class="col-10">
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'import_upload_csv' %}">
                                {% csrf_token %}
                                <input type="file" name="document">
                                <button class="btn btn-primary" type="submit"> Upload Import CSV</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

BBBatScale/core/templates/instances_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}
     <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Configure server" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>

    </section>
{% endblock %}


{% block scripts %}

{% endblock scripts %}

BBBatScale/core/templates/instances_overview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-1">
                <div class="col-12 card">
                    <div class="card-body">
                        {% crispy filter.form filter.form.helper %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title" id="table_desc">{% trans "Server overview" %}<span
                                    class="badge badge-pill badge-primary ml-1">{{ filter.qs.count }}</span></h3>
                            <div class="card-tools">
                                <a class="btn btn-sm btn-default float-right" href="{% url 'instance_create' %}"><em
                                        class="fas fa-plus"></em></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table aria-describedby="table_desc" class="table table-hover table-sm">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">{% trans "Tenant" %}</th>
                                    <th scope="col">{% trans "DNS" %}</th>
                                    <th scope="col">{% trans "State" %}</th>
                                    <th scope="col">{% trans "Datacenter" %}</th>
                                    <th scope="col">{% trans "Participants" %}</th>
                                    <th scope="col">{% trans "Videostreams" %}</th>
                                    <th scope="col">{% trans "Rooms" %}</th>
                                    <th scope="col">{% trans "Utilization" %}</th>
                                    <th scope="col">{% trans "Health Check" %}</th>
                                    <th scope="col" class="text-right">{% trans "Action" %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for instance in filter.qs %}

                                    <tr>
                                        <td>{{ instance.tenant|default_if_none:"-" }}</td>
                                        <td>{{ instance.dns }}</td>

                                        <td>{% include "snippet_instance_state.html" with state=instance.state %}</td>
                                        <td>{{ instance.datacenter }}</td>
                                        <td>{{ instance.get_participant_count }}
                                            / {{ instance.participant_count_max }}</td>
                                        <td>{{ instance.get_videostream_count }}
                                            / {{ instance.videostream_count_max }}</td>
                                        <td>{{ instance.room_set.all.count }}</td>
                                        <td>{% include "snippet_progress_bar.html" with progress=instance.get_utilization_percent %} {{ instance.get_utilization_percent }}%</td>
                                        <td>{{ instance.last_health_check|timesince }}</td>

                                        <td>
                                            <div class="btn-group btn-group-sm float-right">
                                                <a class="btn btn-success"
                                                   href="{% url 'instance_update' instance.pk %}"
                                                   data-toggle="tooltip" data-placement="top"
                                                   title="{% trans "Edit" %}">
                                                    <em class="fas fa-pen"></em>
                                                </a>
                                                <button class="btn btn-danger"
                                                        id="open_delete_instance_modal"
                                                        data-id="{{ instance.pk }}" data-toggle="tooltip"
                                                        data-placement="top"
                                                        title="{% trans "Delete" %}">
                                                    <em class="fas fa-trash-alt"></em>
                                                </button>
                                            </div>

                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>

    </section>




    <div id="delete_instance_modal" class="modal fade" tabindex="-1" role="dialog"
         aria-labelledby="CenterModalLabel"
         aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="CenterModalLabel">{% trans "Delete server" %}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    {% trans "Are you sure you want to delete the server?" %}
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" href=""
                       data-toggle="tooltip" data-placement="top" title="Löschen" id="delete_instance">
                        {% trans "Delete" %}
                    </a>
                    <button type="button" class="btn btn-secondary waves-effect"
                            data-dismiss="modal">{% trans "Cancel" %}</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function () {
            $(document).on('click', '#open_delete_instance_modal', function () {
                $('#delete_instance').attr('href', '/core/instance/delete/' + $(this).data('id'));
                $('#delete_instance_modal').modal('toggle');
            });
        });

    </script>
{% endblock %}

BBBatScale/core/templates/password_change.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Password change form" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>

    </section>


{% endblock %}


{% block scripts %}
{% endblock scripts %}

BBBatScale/core/templates/tenants_overview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-1">
                <div class="col-12 card">
                    <div class="card-body">
                        {% crispy filter.form filter.form.helper %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title" id="table_desc">{% trans "Tenants overview" %}<span
                                    class="badge badge-pill badge-primary ml-1">{{ filter.qs.count }}</span></h3>
                            <div class="card-tools">
                                <a class="btn btn-sm btn-default float-right" href="{% url 'tenant_create' %}"><em
                                        class="fas fa-plus"></em></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table aria-describedby="table_desc" class="table table-hover table-sm">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">{% trans "Name" %}</th>
                                    <th scope="col">{% trans "Scheduling Strategy" %}</th>
                                    <th scope="col">{% trans "Description" %}</th>
                                    <th scope="col">{% trans "Email Notifications" %}</th>
                                    <th scope="col" class="text-right">{% trans "Action" %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for tenant in filter.qs %}
                                    <tr>
                                        <td>{{ tenant.name }}</td>
                                        <td>{{ tenant.get_scheduling_strategy_display }}</td>
                                        <td>{{ tenant.description|default_if_none:"" }}</td>
                                        <td>{{ tenant.notifications_emails }}</td>
                                        <td>
                                            <div class="btn-group btn-group-sm float-right">
                                                <a class="btn btn-success"
                                                   href="{% url 'tenant_update' tenant.pk %}"
                                                   data-toggle="tooltip" data-placement="top"
                                                   title="{% trans "Edit" %}">
                                                    <em class="fas fa-pen"></em>
                                                </a>
                                                <button class="btn btn-danger"
                                                        id="open_delete_tenant_modal"
                                                        data-id="{{ tenant.pk }}" data-toggle="tooltip"
                                                        data-placement="top"
                                                        title="{% trans "Delete" %}">
                                                    <em class="fas fa-trash-alt"></em>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>

    </section>



    <div id="delete_tenant_modal" class="modal fade" tabindex="-1" role="dialog"
         aria-labelledby="CenterModalLabel"
         aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="CenterModalLabel">{% trans "Delete tenant" %}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    {% trans "Are you sure you want to delete the tenant?" %}
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" href=""
                       data-toggle="tooltip" data-placement="top" title="Löschen" id="delete_tenant">
                        {% trans "Delete" %}
                    </a>
                    <button type="button" class="btn btn-secondary waves-effect"
                            data-dismiss="modal">{% trans "Cancel" %}</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>





{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function () {
            $(document).on('click', '#open_delete_tenant_modal', function () {
                $('#delete_tenant').attr('href', '/core/tenant/delete/' + $(this).data('id'));
                $('#delete_tenant_modal').modal('toggle');
            });

        });

    </script>
{% endblock %}